### ISSUE TITLE
NLP resources

### ISSUE THREAD

**Issue by czyzby** [thomasnield/kotlin-data-science-resources#2]
I don't believe you've mentioned any NLP frameworks (like CoreNLP/OpenNLP). This is also another potential `TODO`: provide Kotlin API for a NLP framework, preferably CoreNLP. As far as I know, CoreNLP still provides some features that Spacy does not (like coreference resolution), but it is very much a research tool and I wouldn't call its API exactly developer-friendly. Some predefined pipelines with examples in Kotlin would be really nice.

BTW, you can create a checkboxes list in Markdown using this syntax:

```markdown
- [ ] Do A.
- [ ] Do B.
- [x] Did C.
```

- [ ] Add existing NLP Java frameworks.
- [ ] Consider adding Kotlin API for a NLP framework to `TODO`.

**Comment by thomasnield** [comment]
Thanks, I forgot that syntax for checkboxes. I just added those items although do keep in mind [Komputation](https://github.com/sekwiatkowski/komputation) is one Kotlin NLP framework in existence.

**Comment by czyzby** [comment]
What I meant by `Add existing NLP Java frameworks` is that you can add Stanford CoreNLP to "Java Libaries" section - it should be removed from roadmap.

Anyway, Komputation is not a NLP framework per se, it just provides recurrent/convolutional neural networks implementation and these are commonly used for text processing.

**Comment by thomasnield** [comment]
Ah okay. Ill update tomorrow.

**Comment by czyzby** [comment]
[KotlinNLP](https://github.com/KotlinNLP) is also worth adding to the list.

**Comment by thomasnield** [comment]
Updated. Let me know if I missed anything else.

**Comment by czyzby** [comment]
I'd rethink the categories column, to be honest. "Neural network" (Komputation) can be changed to "deep learning", while "natural language" should be "natural language processing" (CoreNLP, KotlinNLP). DeepLearning4J should definitely go to the deep learning category, as it mainly provides neural networks-based algorithms.

KotlinNLP also provides the [SimpleDNN](https://github.com/KotlinNLP/SimpleDNN) framework, which seems to provide implementations of fully-connected and recurrent neural networks mainly for NLP usage. You can look into that.

**Comment by thomasnield** [comment]
Done.
